version: '3'

services:
  api:
    container_name: ludu-api
    build:
      context: .
    ports:
      - ${API_PORT}:${API_PORT}
    env_file: .env

  nginx:
    container_name: ludu-nginx
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx.conf:/nginx.conf
    depends_on:
      - api
    links:
      - api:api
    ports:
      - 80:80
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - API_PORT=${API_PORT}
      - NGINX_MAX_BODY=${NGINX_MAX_BODY}
    command: /bin/sh -c "rm /etc/nginx/nginx.conf && envsubst < ./nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"